service: noumena-runner-bot-test-2
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-central-1
  memorySize: 128
functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    noPrependStageInUrl: true
